version: "3.8"

services:
  backend-tester:
    image: task-manager-backend:ci
    build: null
    environment:
      JWT_SECRET: ${JWT_SECRET}
    working_dir: /app
    entrypoint: ["sh", "-c"]

  frontend-tester:
    image: task-manager-frontend:ci
    build: null
    working_dir: /usr/src/app
    entrypoint: ["sh", "-c"]
