services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-task_manager}
    volumes:
      - task_manager_db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-task_manager}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./task-manager-backend
      dockerfile: ../docker/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-task_manager}}
      APP_MODULE: ${APP_MODULE:-app.main:app}
      RELOAD: ${RELOAD:-true}
      JWT_SECRET: ${JWT_SECRET}                #
    ports:
      - "8000:8000"
    volumes:
      - ./task-manager-backend/app:/app/app
      - ./task-manager-backend/tests:/app/tests
      - ./task-manager-backend/pyproject.toml:/app/pyproject.toml:ro
      - ./task-manager-backend/uv.lock:/app/uv.lock:ro
      - backend_venv:/app/.venv

    command: ["/app/.venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    entrypoint: ["/app/entrypoint.sh"]
    restart: on-failure

  backend-tester:
    profiles: ['tester']
    build:
      context: ./task-manager-backend
      dockerfile: ../docker/backend/Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET}                #
    volumes:
      - ./task-manager-backend/app:/app/app
      - ./task-manager-backend/tests:/app/tests
      - ./task-manager-backend/pyproject.toml:/app/pyproject.toml:ro
      - ./task-manager-backend/uv.lock:/app/uv.lock:ro
      - backend_venv:/app/.venv

  frontend:
    build:
      context: ./task-manager-frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./task-manager-frontend:/usr/src/app:cached
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
  frontend-tester:
    profiles: ["tester"]
    build:
      context: ./task-manager-frontend
      dockerfile: ../docker/frontend/Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./task-manager-frontend:/usr/src/app:cached
      - /usr/src/app/node_modules

volumes:
  task_manager_db_data:
  backend_venv: