from typing import Protocol, Sequence
from sqlalchemy.orm import Session
from app.models.user import User

class UserRepository(Protocol):
    def create(self, db: Session, *, email: str, full_name: str | None, hashed_password: str) -> User: ...
    def get(self, db: Session, user_id: str) -> User | None: ...
    def get_by_email(self, db: Session, email: str) -> User | None: ...

