[project]
name = "flask_hello_world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[tool.pytest]
testpaths = ["."]