name: Backend CI (task-manager-backend)

on:
  push:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker-compose.yml"
  pull_request:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker-compose.yml"

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build backend image & run tests
    runs-on: ubuntu-latest

    # Job-level env: JWT_SECRET must be created in repo Secrets
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fail fast if JWT_SECRET missing
        run: |
          if [ -z "${JWT_SECRET:-}" ]; then
            echo "::error::JWT_SECRET secret is not provided. Add it at Settings → Secrets and variables → Actions."
            exit 1
          else
            echo "JWT_SECRET present (masked)."
          fi

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build backend image (buildx with GitHub Actions cache)
        working-directory: task-manager
        uses: docker/build-push-action@v4
        with:
          context: ./task-manager-backend
          file: ./docker/backend/Dockerfile
          tags: task-manager-backend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests (compose-run with JWT_SECRET passed into container)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running tests in a one-off container; explicitly passing JWT_SECRET into the container..."
          docker compose run --rm --no-deps \
            -e JWT_SECRET="${JWT_SECRET}" \
            backend uv run pytest .

      - name: Tear down docker-compose resources
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose down --volumes --remove-orphans
