name: Backend CI (task-manager-backend)

# Run only when backend or backend docker config changes
on:
  push:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker-compose.yml"
  pull_request:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker-compose.yml"

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build backend image & run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build backend image (compose)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Building backend image..."
          DOCKER_BUILDKIT=1 docker compose build --progress=plain backend

      - name: Run tests (make test)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running Makefile test target..."
          make test

      - name: Tear down docker-compose resources
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose down --volumes --remove-orphans
