name: Task Manager CI (test-compose based, no entrypoint in CI)

on:
  push:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/task-manager-frontend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker/frontend/**"
      - "task-manager/docker-compose.test.yml"
      - "task-manager/docker-compose.ci.yml"
  pull_request:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/task-manager-frontend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker/frontend/**"
      - "task-manager/docker-compose.test.yml"
      - "task-manager/docker-compose.ci.yml"

concurrency:
  group: task-manager-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend — build image & run tests (no entrypoint)
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build backend image (buildx with cache)
        uses: docker/build-push-action@v4
        with:
          context: ./task-manager/task-manager-backend
          file: ./task-manager/docker/backend/Dockerfile
          tags: task-manager-backend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run backend tests (use built image)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running backend tests using docker-compose.test.yml + docker-compose.ci.yml"
          docker compose -f docker-compose.test.yml -f docker-compose.ci.yml run --rm --no-deps \
            -e JWT_SECRET="${JWT_SECRET}" \
            backend-tester

      - name: Tear down (backend)
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose -f docker-compose.test.yml -f docker-compose.ci.yml down --volumes --remove-orphans

  frontend:
    name: Frontend — build image & run tests (test-compose)
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build frontend image (buildx with cache)
        uses: docker/build-push-action@v4
        with:
          context: ./task-manager/task-manager-frontend
          file: ./task-manager/docker/frontend/Dockerfile
          tags: task-manager-frontend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run frontend tests (use built image)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running frontend tests using docker-compose.test.yml + docker-compose.ci.yml"
          docker compose -f docker-compose.test.yml -f docker-compose.ci.yml run --rm --no-deps \
            frontend-tester

      - name: Tear down (frontend)
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose -f docker-compose.test.yml -f docker-compose.ci.yml down --volumes --remove-orphans
