name: Task Manager CI

on:
  push:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/task-manager-frontend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker/frontend/**"
      - "task-manager/docker-compose.yml"
  pull_request:
    paths:
      - "task-manager/task-manager-backend/**"
      - "task-manager/task-manager-frontend/**"
      - "task-manager/docker/backend/**"
      - "task-manager/docker/frontend/**"
      - "task-manager/docker-compose.yml"

concurrency:
  group: task-manager-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend — build & test
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci
      # JWT_SECRET must be set in repo Secrets
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fail fast if JWT_SECRET missing
        run: |
          if [ -z "${JWT_SECRET:-}" ]; then
            echo "::error::JWT_SECRET secret is not provided. Add it at Settings → Secrets and variables → Actions."
            exit 1
          else
            echo "JWT_SECRET present (masked)."
          fi

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build backend image (buildx with cache)
        uses: docker/build-push-action@v4
        with:
          context: ./task-manager/task-manager-backend
          file: ./task-manager/docker/backend/Dockerfile
          tags: task-manager-backend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run backend tests (compose-run, pass JWT_SECRET)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running backend tests in a one-off container; passing JWT_SECRET..."
          docker compose run --rm --no-deps \
            -e JWT_SECRET="${JWT_SECRET}" \
            backend-tester uv run pytest .

      - name: Tear down (backend)
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose down --volumes --remove-orphans

  frontend:
    name: Frontend — build & test
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: task-manager-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker CLI and Compose available
        run: |
          docker version
          docker compose version

      - name: Build frontend image (buildx with cache)
        uses: docker/build-push-action@v4
        with:
          context: ./task-manager/task-manager-frontend
          file: ./task-manager/docker/frontend/Dockerfile
          tags: task-manager-frontend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run frontend tests (compose-run, Vitest CI)
        working-directory: task-manager
        run: |
          set -euo pipefail
          echo "Running frontend tests in a one-off container (vitest run --coverage)..."
          docker compose run --rm --no-deps \
            frontend-tester sh -c "npm run test:ci"

      - name: Tear down (frontend)
        if: always()
        working-directory: task-manager
        run: |
          set -euo pipefail
          docker compose down --volumes --remove-orphans
